### ISSUE TITLE
GC5035 dkms

### ISSUE THREAD

**Issue by junocomp** [intel/ipu6-drivers#142]
```
BUILT_MODULE_NAME[20]="gc5035"
BUILT_MODULE_LOCATION[20]="drivers/media/i2c"
DEST_MODULE_LOCATION[20]="/updates"
```

Needs to be added to dkms.conf

**Comment by mburucuyapy** [comment]
Any chance to add this?

**Comment by andyyeh75** [comment]
Hi, may we know which laptop model you are asking for? Thanks.

**Comment by mburucuyapy** [comment]
@andyyeh75 is our tablet, Juno Tab 1 - released 2022

**Comment by andyyeh75** [comment]
Hi @mburucuyapy 
Sorry, we could only directly support the customer devices with the Ubuntu/RedHat Cert hardware, or they are currently working on it.  Thanks for your understanding.

[Ubuntu Cert Laptop](https://ubuntu.com/certified/laptops)
[Red Hat certified hardware](https://catalog.redhat.com/hardware)
