### ISSUE TITLE
missing link-frequencies device property when compiled against kernel < v6.6

### ISSUE THREAD

**Issue by vicamo** [intel/ipu6-drivers#232]
When compiled with **CONFIG_IPU_ISYS_BRIDGE** enabled (thus < v6.6), `cio2_supported_sensors` config array is used and many sensors inside have no link-freq defined. This fails hwcfg check then:
```
kernel: ov02c10 i2c-OVTI02C1:00: no link frequencies defined
kernel: ov02c10 i2c-OVTI02C1:00: failed to check hwcfg: -22
kernel: ov02c10: probe of i2c-OVTI02C1:00 failed with error -22
```
Settings from https://github.com/intel/ipu6-drivers/blob/master/patch/v6.8/0003-media-ipu-bridge-Support-more-sensors.patch solves this issue.

**Comment by hao-yao** [comment]
Should be fixed by [this](https://github.com/hao-yao/ipu6-drivers/commit/df7ef4534c8a908279dc2a7498051f834282f275).
