### ISSUE TITLE
MIPI Camera Drivers Compatibility for ASUS VivoBook Slate 13

### ISSUE THREAD

**Issue by rautyrauty** [intel/ipu6-drivers#238]
The CPU of this laptop has MIPI camera control, and neither of the two cameras work on Linux. But they work on Windows.
What can I do to solve the problem? Are intel interested in the solution?
The dmesg logs look like in this issue: https://github.com/intel/ipu6-drivers/issues/228#issuecomment-2132039519

Tested on ubuntu with https://launchpad.net/ubuntu/+source/ipu6-drivers, sosreport: [sosreport-kubuntu-2024-06-08-fdavxlx.zip](https://github.com/user-attachments/files/15764215/sosreport-kubuntu-2024-06-08-fdavxlx.zip). Also tested on ALT linux with kernel 6.8.12.

**Comment by ChenYuYeh** [comment]
Hi,

Same as #202 for HP and #237 for Samsung, we have observed that even those designs with IPU6 Camera but has no Ubuntu cert granted. As you may know that there are camera, lens, and circuit hardware dependency, it takes effort from PC vendor and Intel to enable the function together.  

Not sure Asus customer service will give you the response, but there is No other way to make it happen on your Asus device.

> The CPU of this laptop has MIPI camera control, and neither of the two cameras work on Linux. But they work on Windows.
> What can I do to solve the problem? Are intel interested in the solution?
> The dmesg logs look like in this issue: https://github.com/intel/ipu6-drivers/issues/228#issuecomment-2132039519
> 
> Tested on ubuntu with https://launchpad.net/ubuntu/+source/ipu6-drivers, sosreport: [sosreport-kubuntu-2024-06-08-fdavxlx.zip](https://github.com/user-attachments/files/15764215/sosreport-kubuntu-2024-06-08-fdavxlx.zip). Also tested on ALT linux with kernel 6.8.12.
>

**Comment by rautyrauty** [comment]
I wrote to the ASUS technical support service asking for help to solve this problem.

**Comment by rautyrauty** [comment]
@ChenYuYeh What kind of information do we want to get from ASUS to add support?

**Comment by ChenYuYeh** [comment]
@rautyrauty 
Supposedly Asus can reply you whether they are seeking for obtaining the certificate by Canonical? If just be mute then it means there is no plan yet.

**Comment by rautyrauty** [comment]
Well, ASUS replied that they were not going to support linux. Is there only one way now - reverse engineering?

**Comment by rautyrauty** [comment]
Can't we get the information we need through reverse engineering of drivers? I can disassemble the laptop if necessary.

**Comment by ChenYuYeh** [comment]
@rautyrauty  I don't think it is HW related. So far the integration should be involved with BIOS configuration (I have seen in some cases BIOS config is wrong but works in Windows but failed in Linux!), upstream kernel driver implementation, and few xml files required to be modified in userspace. PC vendor would have to drive to make the camera work both on Windows and Linux.
