### ISSUE TITLE
>6.11.10 regression in intel_ipu6: CPU lockup

### ISSUE THREAD

**Issue by CosmicToast** [intel/ipu6-drivers#312]
On Fedora 41 (kernel versions >6.11.10), intel_ipu6_isys (or intel_ipu6, one of the two; I resolved this by blacklisting both) causes a soft CPU lockup.
For now I've been continuing to use 6.11.10 (since I do need access to my IPU6 camera) as a workaround.
I'm attaching a dmesg log from one such boot.
It looks like memory corruption to me, going from the `list_del corruption` message, that list looks obviously wrong to me.
[dmesg.log](https://github.com/user-attachments/files/18183295/dmesg.log)

Please do let me know if I can provide any more information that might be useful, I couldn't easily find any documentation as to the preferred issue details/formats in the repo.

**Comment by sgruszka** [comment]
Hi, this known bug and the problem is fixed if 6.12.5 .
