### ISSUE TITLE
Please add github-ci with daily builds against Ubuntu Mainline Kernel PPA

### ISSUE THREAD

**Issue by xnox** [intel/ipu6-drivers#6]
Please add github-ci / github actions with daily builds against Ubuntu Mainline Kernel PPA

Such that daily builds of the drivers are attempted against daily mainline kernel builds, to ensure that this dkms module remains usable whenever upstream kernel is changing.

**Comment by cjechlitschek** [comment]
@xnox : is this what you had in mind?
